FROM python:3.12-slim

RUN pip install \
    "supabase>=2.30.0" \
    "python-dotenv>=1.2.2" \
    "requests>=2.34.2"
WORKDIR /app

ENV PYTHONPATH="/app"
COPY ./data /app/data
COPY ./src/class_file.py /app/src/class_file.py
COPY ./src/logs.py /app/src/logs.py
COPY  main.py /app 

