
FROM apache/airflow:2.10.4-python3.12


USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-jre-headless \
    gcc \
    python3-dev \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


USER airflow
COPY ./src/logs.py /opt/airflow/logs.py

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir pyspark==3.5.0 supabase==2.30.0 python-dotenv==1.2.2 requests==2.34.2