FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir dbt-postgres>=1.10.0

COPY ./dbt /app/dbt
COPY ./packages.yml /app/packages.yml
COPY ./package-lock.yml /app/package-lock.yml
COPY ./dbt_project.yml /app/dbt_project.yml
COPY ./profiles.yml /app/profiles.yml   
RUN dbt deps
CMD ["dbt", "debug"]