version: 2

sources:
  - name: fonte_supabase    
    schema: public          
    tables:
      - name: raw_csv       
        description: "Dados do arquivo csav."

      - name: raw_ibge
        description: "Dados do ibge"

        